export const SHOW_PHONES = 'SHOW_PHONES';
export const SHOW_PHONE_DETAILS = 'SHOW_PHONE_DETAILS';

export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAILURE = 'DATA_FAILURE';